### ISSUE TITLE
console.log is not a good substitute for dd

### ISSUE THREAD

**Issue by hackel** [appstract/dd.js#2]
As I'm sure you know, console.log doesn't print a snapshot of the variable at that time, which means that later code can change the result when you expand objects in a browser.  I've seen various solutions to this, such as `JSON.parse(JSON.stringify(value))`, and I won't claim what is the best,  but a proper dump function should definitely print objects exactly as they are at that moment in time.

**Comment by ovanschie** [comment]
I don't understand why console log wouldn't print a snapshot. You are logging the value at the time of logging right?

**Comment by hackel** [comment]
Because you're just passing a reference to an object to console.log.  The reference itself does not change, however the browser will not evaluate the contents of the object until it is actually expanded, at which point its contents may have changed.  This is a pretty common Javascript debugging issue.
