### ISSUE TITLE
DD() stops execution

### ISSUE THREAD

**Issue by slavensaka** [appstract/dd.js#3]
```
      var foo = "Test1";
    	var bar = "Test2";
//       dump(foo,bar);
    	dd(foo, bar); 
```
When I use dump(foo, bar); works fine. On using dd(foo,bar) I get this error 

> "Stopped execution because dd(), use dump() if you want to proceed"

Why is this error thrown?

**Comment by ovanschie** [comment]
dd stands for 'dump and die', so Stopped execution because dd...
